# KPMG Virtual Internship
#### Case Study
**Sprocket Central Pty Ltd Data Set**<br>
<br>
**Author:** Ingrid Cadu<br>
**Update:** Apr 25, 2022<br>

Note.<br>
This is the part two of KPMG Virtual Internship Case Study.<br>
Please, check out the part one for more information about the others visualizations.

In [1]:
#libraries

import numpy as np
import pandas as pd
import geopandas as gpd
import json
from urllib.request import urlopen
import plotly.express as px
import plotly.graph_objects as go

## Choropleth Map

In [2]:
#get AU geometry
with urlopen('https://raw.githubusercontent.com/rowanhogan/australian-states/master/states.geojson') as response:
    counties = json.load(response)


    
#counties["features"][0]['properties'].keys()
#counties["features"][0]

In [3]:
counties["features"][0]['properties'].keys()

dict_keys(['STATE_CODE', 'STATE_NAME'])

In [4]:
#getting stat data

stat = pd.read_csv("./data/stats_bike_17.csv")
stat = stat.rename(columns={'name':'STATE_NAME'})

In [5]:
stat

,state,STATE_NAME,lat,long,rode_past_week_commuting,rode_past_week_education,without_working_bike,recreation,transport,Comfortable_area,participation_month,participation_year,total
0,NWS,New South Wales,-31.840233,145.612793,10.9,2.5,48.0,88,19,49,-2.9,-0.9,1088
1,ACT,Australian Capital Territory,-35.473469,149.012375,13.0,25.0,33.0,69,43,84,0.0,0.0,994
2,NT,Northern Territory,-19.491411,132.550964,15.2,15.4,30.0,76,36,75,-1.5,0.2,730
3,QLD,Queensland,-20.917574,142.702789,4.0,19.6,43.5,75,40,66,3.4,4.2,1176
4,SA,South Australia,-30.000233,136.209152,9.3,12.2,49.5,81,30,55,-0.4,-2.7,1101
5,TAS,Tasmania,0.000000,0.000000,7.0,3.0,46.0,86,17,56,-1.0,-3.4,1252
6,VIC,Victoria,-37.020100,144.964600,10.4,11.5,41.0,76,34,55,-3.6,-5.0,1319
7,WA,Western Australia,-25.042261,117.793221,9.0,16.7,38.9,85,35,57,-13.1,-9.4,1070

In [25]:
#Plotting data // CHANGE THE VAR BY A BOX_SELECTION

max_color=stat.total.max()
min_color=stat.total.min()

fig = go.Figure(go.Choroplethmapbox(geojson=counties, 
                                    locations=stat.STATE_NAME, 
                                    z=stat.total,
                                    text=stat.state,
                                    featureidkey="properties.STATE_NAME",
                                    colorscale="Redor", 
                                    zmin=min_color, 
                                    zmax=max_color,
                                    marker_opacity=0.8, 
                                    marker_line_width=0,
                                    name="Total Sample (n)",
                                    hovertemplate="%{text}<br>%{z}%"))

fig.update_layout(mapbox_style="carto-positron",
                  mapbox_zoom=2.6, 
                  mapbox_center = {"lat": -25.2744, "lon": 133.7751},
                 mapbox_layers=[fill="#fff"])
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.update_traces(colorbar=dict(len=0.5,
                                ticks='inside',
                                thickness=10,
                                ticklen=0,
                                outlinewidth=0),
                  selector=dict(type='choroplethmapbox'))

SyntaxError: invalid syntax (3597331241.py, line 22)

In [ ]:
#save as html the plot
#fig.write_html("./data/total.html")